<?php


$title = 'Add new Fournisseur';
$this->headTitle($title);
?>

<?php
$form->setAttribute('action', $this->url('fournisseur', array('action' => 'add')));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
$mobile = $form->get('mobile');
$intitule = $form->get('intitule');
$compte = $form->get('compte');
$email = $form->get('email');

$sub = $form->get('submit');
/*
echo $this->formRow($form->get('mobile'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();*/

?>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <?php echo $this->escapeHtml($title); ?>
    </div>
    <div class="panel-body " style="background-color:#b7c5df">
        <div class="row">
            <div class="col-md-4" >
                <label for=""><?= $this->formLabel($compte); ?></label>
                <?= $this->formelement($compte); ?>
                <small class="form-text text-muted">    <?= $this->formElementErrors($compte); ?></small>
            </div>
        </div>

        <div class="row" >

            <div class="col-md-3">
                <label for=""><?= $this->formLabel($intitule); ?></label>
                <?= $this->formelement($intitule); ?>
                <small class="form-text text-muted">    <?= $this->formElementErrors($intitule); ?></small>

            </div>


        </div>

        <div class="row">
            <div class="col-md-3">
                <label for="">
                    <?= $this->formLabel($mobile); ?>
                </label>

                <?= $this->formelement($mobile); ?>

                <small class="form-text text-muted">
                    <?= $this->formElementErrors($mobile); ?>
                </small>
            </div>
            <div class="col-md-3">
                <label for="">
                    <?= $this->formLabel($email); ?>
                </label>

                <?= $this->formelement($email); ?>

                <small class="form-text text-muted">
                    <?= $this->formElementErrors($email); ?>
                </small>
            </div>


        </div>



    </div>

    <div class="panel-body">



    </div>
    <div class="panel-footer" style="background-color:white">

        <div class="row">
            <div class="col-md-2" >
                <?= $this->formelement($sub); ?>

            </div>
        </div>

    </div>
    <!-- List group
    <ul class="list-group">
        <li class="list-group-item"></li>
        <li class="list-group-item"></li>
        <li class="list-group-item"></li>
        <li class="list-group-item"></li>
        <li class="list-group-item"></li>
    </ul>-->


</div>













<?php
echo $this->form()->closeTag();

?>

<script>


</script>


