


<?php
// module/Album/view/album/album/index.phtml:

$title = 'List Fournisseurs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-primary" href="<?php echo $this->url('fournisseur', array('action'=>'add'));?>">Add new fournisseur</a>
</p>

<table class="table table-striped" width="auto">
    <tr>
        <th>N° Compte</th>
        <th>Intitulé</th>
        <th>&nbsp;Mobile </th>
        <th>Email </th>
        <th></th>
    </tr>
    <?php foreach ($fournisseurs as $fournisseur) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($fournisseur->compte);?></td>
            <td><?php echo $this->escapeHtml($fournisseur->intitule);?></td>
            <td><?php echo $this->escapeHtml($fournisseur->mobile);?></td>
            <td><?php echo $this->escapeHtml($fournisseur->email);?></td>

            <td>
                <div class="dropdown show">

                    <a class="btn btn-info" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Action
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="<?php echo $this->url('fournisseur',
                            array('action'=>'edit', 'id' => $fournisseur->id));?>"><b> Edit </b></a>&nbsp<br>
                        <a class="dropdown-item" href="<?php echo $this->url('fournisseur',
                            array('action'=>'delete', 'id' => $fournisseur->id));?>"> <b> Delete</b>  </a>

                    </div>
                </div>




            </td>
        </tr>
    <?php endforeach; ?>
</table>